# dev:
#   doctrine:
#     class: sfDoctrineDatabase
# # test:
# #   doctrine:
# #     class: sfDoctrineDatabase
# #     param:
# #       dsn: 'mysql:host=host.docker.internal:8002;dbname=jobeet'
# #       username: jobeet
# #       password: jobeet
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=host.docker.internal:8002;dbname=jobeet'
      username: jobeet
      password: jobeet
